[project]
name = "claude-agent"
version = "0.1.0"
description = ""
authors = [
    {name = "Henry Rothenberg",email = "hsr205@aol.com"}
]
requires-python = ">=3.12"
dependencies = [
    "anthropic (>=0.107.1,<0.108.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
