from typing import Any

from anthropic import Anthropic
from anthropic.types import Message

from agent.specialized_agent import SpecializedAgent
from config.config import Settings
from logger.logger import AppLogger
from mcp_servers.finance_mcp_server import FinanceMCPServer


class AgentOrchestrator:

    def __init__(self) -> None:
        self._config: Settings = Settings()
        self._client: Anthropic = Anthropic(api_key=self._config.claude_api_key)
        self._mcp_server: FinanceMCPServer = FinanceMCPServer()

        # Initialize subagents with hyper-focused system prompts
        self._data_fetching_agent: SpecializedAgent = SpecializedAgent(
            name_str="Data_Fetching_Agent",
            client=self._client,
            model_name_str=self._config.claude_model_name,
            system_prompt="""
            You are the Data Fetching / Downloading Analyst. 
            Extract stock data based on the tickers / date ranges, and use the download_historical_stock_data tool to download the CSVs to the appropriate directories.
            """
        )

        # self._monte_carlo_simulation: SpecializedAgent = SpecializedAgent(
        #     name_str="Monte_Carlo_Agent",
        #     client=self._client,
        #     model_name_str=self._config.claude_model_name,
        #     # TODO: Finish this system prompt
        #     system_prompt="using the execute_monte_carlo_simulation  method"
        # )

        # self._visualization_agent: SpecializedAgent = SpecializedAgent(
        #     name_str="Visual_Construction_Agent",
        #     client=self._client,
        #     model_name_str=self._config.claude_model_name,
        #     # TODO: Finish this system prompt
        #     system_prompt="You are the Visual Construction Specialist. Create a visual for the data provided from the monte carlo simulation using the create_visualization_for_data_analysis method"
        # )

        self._logger = AppLogger.get_logger(self.__class__.__name__)

    async def run_workflow_async(self, user_request: str) -> None:
        self._logger.info("Resolving server application capability schemas via Event Loop...")

        # Pre-resolve the tools asynchronously using the public interface safely
        download_historical_stock_schema_dict: dict = await self._resolve_tool_schema(
            tool_name="download_historical_stock_data")
        # data_aggregation_schema:dict = await self._resolve_tool_schema(tool_name="")
        # notify_schema:dict = await self._resolve_tool_schema(tool_name="")

        self._logger.info("All tool protocol contexts successfully resolved. Launching pipeline.")

        # Step 1: The Sieve Analyst (Data Extraction)
        self._logger.info("Step 1: Routing to Fetching / Download  Agent.")
        claude_response_message: Message = self._data_fetching_agent.execute_turn(prompt=user_request,
                                                                                  schema_context=download_historical_stock_schema_dict)

        if claude_response_message.stop_reason == "tool_use":
            # Extract out the requested tool and input parameters generated by Claude
            tool_use_block = next(b for b in claude_response_message.content if b.type == "tool_use")
            requested_tool_name: str = tool_use_block.name
            requested_arguments: dict[str, Any] = tool_use_block.input

            self._logger.info(f"[ORCHESTRATOR INTERCEPT] Claude confirmed intent to run: '{requested_tool_name}'")
            self._logger.info(f"[ORCHESTRATOR INTERCEPT] Extracted parameters payload: {requested_arguments}")

            # Step 2: Route directly to local code to perform the physical file write operation
            if requested_tool_name == "download_historical_stock_data":
                # Look up the native Python function wrapped by FastMCP
                internal_tool_object = await self._mcp_server.mcp.get_tool(requested_tool_name)

                self._logger.info("[ORCHESTRATOR] Directing local capability server to write data matrix...")

                execution_result: str = internal_tool_object.fn(
                    ticker_list=requested_arguments.get("ticker_list", []),
                    start_date_str=requested_arguments.get("start_date_str", ""),
                    end_date_str=requested_arguments.get("end_date_str", ""),
                    csv_path=requested_arguments.get("csv_path", "")
                )

                self._logger.info(f"[ORCHESTRATOR COMPLETE] Execution outcome secured: {execution_result}")
        else:
            self._logger.warning("[ORCHESTRATOR] Claude completed turn without generating a tool request block.")

        # execute_montecarlo_simulation_schema_dict: dict = await self._resolve_tool_schema(
        #     tool_name="execute_montecarlo_simulation")

        # TODO: Implement execute_montecarlo_simulation method as an agent
        # # Step 2: Monte Carlo Simulation
        # self._logger.info("Step 3: Routing to Notification Agent.")
        # monte_carlo_directive: str = "Execute the monte carlo simulation for 1,000 episodes"
        # self._notification_agent.execute_turn(
        #     prompt=monte_carlo_directive,
        #     schema_context=execute_montecarlo_simulation_schema_dict,
        # )

        # visualization_schema_dict: dict = await self._resolve_tool_schema(
        #     tool_name="execute_montecarlo_simulation")

        # TODO: Implement create_data_visualization method as an agent
        # # Step 3: The Visualization Specialist
        # self._logger.info("Step 3: Routing to Visualization Agent.")
        # notify_directive: str = ""
        # self._notification_agent.execute_turn(
        #     prompt=notify_directive,
        #     schema_context=visualization_schema_dict,
        # )

        self._logger.info("Pipeline complete. Workflow successfully terminated.")

    async def _resolve_tool_schema(self, tool_name: str) -> dict[str, str | dict[str, str | list[str]]]:
        internal_tool_wrapper = await self._mcp_server.mcp.get_tool(tool_name)

        if internal_tool_wrapper is None:
            raise KeyError(f"Failed to resolve execution context: Tool '{tool_name}' not registered on server.")

        mcp_contract_protocol = internal_tool_wrapper.to_mcp_tool()

        return {
            "name": mcp_contract_protocol.name,
            "description": mcp_contract_protocol.description,
            "input_schema": mcp_contract_protocol.inputSchema
        }
